# -*- coding: utf-8 -*-
"""Castle Peak Slope Representation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tYAVQqXFHc6PRKUIcSxUwENA6PEILH2E
"""

!pip install richdem
!pip install elevation

from google.colab import drive
drive.mount('/content/gdrive')

import os
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import elevation
import richdem as rd

dem_path = "/content/gdrive/MyDrive/Search and Tracking/Castle Peak.tif"

shasta_dem = rd.LoadGDAL(dem_path)
shasta_dem[10,10]

plt.imshow(shasta_dem, interpolation='none')
plt.colorbar()
plt.show()

slope = rd.TerrainAttribute(shasta_dem, attrib='slope_riserun', zscale=0.00001)
rd.rdShow(slope, axes=False, cmap='magma', figsize=(8, 5.5))
plt.show()

slope.max()

cost = 0.6*np.exp(3.5*np.abs(slope - 0.05))
print(cost.max(), cost.min(), cost.shape)

plt.imshow(np.minimum(cost,20), interpolation='none')
plt.colorbar()
plt.show()

cost.max()

slope/1000